Replyto and return path
moreonion/email_check pull request #2
Opened 2018-01-15 19:47 UTC by alex-mo

* Reply to fix
* set a *valid* Return-Path
* Tests

NB: this changes the behaviour with `Reply-To` (it is not enforced to the variable any more)

2018-01-18 19:11 UTC, alex-mo commented
More changes:
- refactor and test the mail pattern matching
- fix for long TLD
- change behaviour with multiple from addresses
- tests for replyto and multiple from addresses
- Drupal comment style

2018-01-19 15:17 UTC, torotil requested changes
Thanks for fixing this and writing all those tests! Could you also fix the coding-style issues I’ve pointed out?

2018-01-19 15:17 UTC, torotil commented on email_check.module
> +    // make sure site_mail and site_mail_domain are consistend
Comments should be whole sentences. (phpcs-drupal)

2018-01-19 15:17 UTC, torotil commented on email_check.module
> +    } else {
The trailing `{` should be on a separate line. (phpcs)

2018-01-19 15:17 UTC, torotil commented on email_check.module
> +        } else {
The `{` should be on a separate line.

2018-01-19 15:17 UTC, torotil commented on email_check.module
> +  // the Drupal default is to use the messages 'From' address
Comments should be whole sentences … (phpcs)

2018-01-19 15:17 UTC, torotil commented on tests/MailAlterTest.php
> +   * Default is the site_mail.
Function doc summary should be 1 line (optionally) followed by a blank line and the rest of the doc. (phpcs)

There is many more instances of that in here.

2018-01-19 15:17 UTC, torotil commented on tests/MailAlterTest.php
> +  // treat as primary --> replyto is set
Missing function doc. (phpcs) Many more instances of this in the tests.

2018-01-19 16:18 UTC, torotil approved these changes

2018-01-19 16:18 UTC, torotil commented
Never mind I’ve fixed the coding-style issues myself. @alex-mo Could you verify that the doc-strings I’ve modified are still correct?

2018-01-22 13:21 UTC, alex-mo commented
Ah yeah. Forgot running `phpcs`...

2018-01-22 14:00 UTC, alex-mo commented
Checked the comments and changed two: the `email_check` only looks for the first address (and not if any is in the mail domain), when multiple From-addresses are given...

2018-01-22 14:01 UTC, merged